### ISSUE TITLE
Mcmod parser error

### ISSUE THREAD

**Issue by LucaIsGenius** [CIJHN/ILauncher#15]
TypeError: Cannot read property 'childNodes' of undefined

When I fetch the mod detail in [mcmod](https://github.com/CIJHN/ILauncher/blob/master/src/main/services/mcmod.js)'s function fetchDetail

This bug doesn't happen all the time, but some mods will toggle this.

**Comment by PhoebezZ** [comment]
I have fixed it, please test it again.

**Comment by LucaIsGenius** [comment]
Its done, Thanks!
